name: Build NanoLimbo and upload jar to Release 

on:
  push:
    branches: 
      - base
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew clean shadowJar

      - name: Prepare JAR
        id: prepare_jar
        run: |
          JAR_PATH=$(find build/libs -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -n 1)
          cp "$JAR_PATH" ./server.jar
          echo "JAR_SIZE=$(ls -lh ./server.jar | awk '{print $5}')" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NanoLimbo-artifact
          path: server.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: NanoLimbo-artifact

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: server.jar
          tag_name: ${{ github.ref_name }}
          name: "NanoLimbo ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
